name: 'stop_search_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  stop_search_project:
    # Defining staging and intermediate as views
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    # Defining marts as tables
    marts:
      +materialized: table
