version: 2

sources:
  - name: raw
    database: SNOWFLAKE_LEARNING_DB
    schema: PUBLIC
    tables:
      - name: STOP_SEARCH_STAGING
      - name: LSOA_STAGING
      - name: LSOA_DEMOGRAPHICS_STAGING
      - name: IMD_2025_LSOA_STAGING
