version: 2

models:

  ###############################################################
  # DIMENSION TABLES
  ###############################################################

  - name: ode_dim
    description: "Officer-defined ethnicity dimension"
    columns:
      - name: ode_id
        tests:
          - unique
          - not_null

  - name: sde_dim_ss
    description: "Self-defined ethnicity dimension for stop & search"
    columns:
      - name: sde_id
        tests:
          - unique
          - not_null

  - name: sde_dim_demo
    description: "Self-defined ethnicity dimension for demographics"
    columns:
      - name: sde_id
        tests:
          - unique
          - not_null

  - name: forces_dim
    description: "Police forces dimension"
    columns:
      - name: force_id
        tests:
          - unique
          - not_null

  - name: legislation_dim
    description: "Legislation dimension"
    columns:
      - name: leg_id
        tests:
          - unique
          - not_null

  - name: outcome_dim
    description: "Outcome dimension"
    columns:
      - name: outcome_id
        tests:
          - unique
          - not_null

  - name: search_object_dim
    description: "Search object dimension"
    columns:
      - name: obj_id
        tests:
          - unique
          - not_null

  - name: fact_lsoa
    description: "LSOA geography table"
    columns:
      - name: lsoa_code
        tests:
          - unique
          - not_null


  ###############################################################
  # FACT TABLES
  ###############################################################

  - name: fact_stop_search
    description: "Fact table containing stop and search events"
    columns:

      - name: ode_id
        tests:
          - relationships:
              arguments:
                to: ref('ode_dim')
                field: ode_id
              where: "ode_id IS NOT NULL"

      - name: sde_id
        tests:
          - relationships:
              arguments:
                to: ref('sde_dim_ss')
                field: sde_id
              where: "sde_id IS NOT NULL"

      - name: force_id
        tests:
          - relationships:
              arguments:
                to: ref('forces_dim')
                field: force_id
              where: "force_id IS NOT NULL"

      - name: leg_id
        tests:
          - relationships:
              arguments:
                to: ref('legislation_dim')
                field: leg_id
              where: "leg_id IS NOT NULL"

      - name: outcome_id
        tests:
          - relationships:
              arguments:
                to: ref('outcome_dim')
                field: outcome_id
              where: "outcome_id IS NOT NULL"

      - name: obj_id
        tests:
          - relationships:
              arguments:
                to: ref('search_object_dim')
                field: obj_id
              where: "obj_id IS NOT NULL"

      - name: lsoa_code
        tests:
          - relationships:
              arguments:
                to: ref('fact_lsoa')
                field: lsoa_code
              where: "lsoa_code IS NOT NULL"


  - name: fact_demographics
    description: "LSOA × ethnicity population counts"
    columns:

      - name: lsoa_code
        tests:
          - relationships:
              arguments:
                to: ref('fact_lsoa')
                field: lsoa_code

      - name: sde_id
        tests:
          - relationships:
              arguments:
                to: ref('sde_dim_demo')
                field: sde_id


  - name: fact_imd
    description: "IMD indicator scores per LSOA"
    columns:

      - name: lsoa_code
        tests:
          - relationships:
              arguments:
                to: ref('fact_lsoa')
                field: lsoa_code
