version: 2

models:
  # ===============================
  # FACT TABLES
  # ===============================

  - name: fact_stop_search
    description: "Each record represents a single stop and search event."
    columns:
      - name: age_range
        description: "Age range of the individual stopped."
      - name: ode_id
        description: "Foreign key to officer-defined ethnicity dimension."
        tests:
          - relationships:
              to: ref('ode_dim')
              field: ode_id
      - name: sde_id
        description: "Foreign key to self-defined ethnicity dimension (stop and search)."
        tests:
          - relationships:
              to: ref('sde_dim_ss')
              field: sde_id
      - name: force_id
        description: "Foreign key to police force dimension."
        tests:
          - relationships:
              to: ref('forces_dim')
              field: force_id
      - name: leg_id
        description: "Foreign key to legislation dimension."
        tests:
          - relationships:
              to: ref('legislation_dim')
              field: leg_id
      - name: outcome_id
        description: "Foreign key to outcome dimension."
        tests:
          - relationships:
              to: ref('outcome_dim')
              field: outcome_id
      - name: obj_id
        description: "Foreign key to search object dimension."
        tests:
          - relationships:
              to: ref('search_object_dim')
              field: obj_id
      - name: lsoa_code
        description: "Foreign key to LSOA table."
        tests:
          - relationships:
              to: ref('fact_lsoa')
              field: lsoa_code
      - name: search_date
        description: "Date and time of the stop and search."
      - name: gender
        description: "Gender of the person stopped."
      - name: outcome_linked_to_object
        description: "Boolean indicating if the outcome was linked to the search object."
      - name: removal_clothing
        description: "Boolean indicating if more than outer clothing was removed."

  - name: fact_demographics
    description: "Ethnicity-based population counts per LSOA."
    tests:
      - unique:
          column_name: "(lsoa_code || '-' || sde_id)"
    columns:
      - name: lsoa_code
        description: "Foreign key to LSOA table."
        tests:
          - relationships:
              to: ref('fact_lsoa')
              field: lsoa_code
      - name: sde_id
        description: "Foreign key to self-defined ethnicity dimension (demographics)."
        tests:
          - relationships:
              to: ref('sde_dim_demo')
              field: sde_id
      - name: pop_count
        description: "Population count for this ethnicity in the LSOA."

  - name: fact_imd
    description: "Index of Multiple Deprivation metrics per LSOA."
    columns:
      - name: lsoa21cd
        description: "LSOA code & Foreign key to LSOA table."
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('fact_lsoa')
              field: lsoa_code
      - name: lsoa21nm
        description: "The name of the LSOA area"
      - name: imd_rank
        description: "IMD ranking where 1 is the most deprived"
      - name: imd_decile
        description: "IMD decile where 1 is the most deprived (value of 1-10)"

  - name: fact_lsoa
    description: "Base geographic table for LSOA boundaries and metadata."
    columns:
      - name: lsoa_code
        description: "Primary key for LSOA area."
        tests:
          - unique
          - not_null


  # ===============================
  # DIMENSIONS
  # ===============================

  - name: ode_dim
    description: "Officer-defined ethnicity categories."
    columns:
      - name: ode
        tests:
          - unique
          - not_null

  - name: sde_dim_ss
    description: "Self-defined ethnicity categories used in stop and search records."
    columns:
      - name: sde
        tests:
          - unique
          - not_null

  - name: sde_dim_demo
    description: "Self-defined ethnicity categories used in demographics data."
    columns:
      - name: sde
        tests:
          - unique
          - not_null

  - name: forces_dim
    description: "Police force names."
    columns:
      - name: force_name
        tests:
          - unique
          - not_null

  - name: legislation_dim
    description: "Legislation references under which searches are conducted."
    columns:
      - name: legislation
        tests:
          - unique
          - not_null

  - name: outcome_dim
    description: "Outcomes of stop and search events."
    columns:
      - name: outcome
        tests:
          - unique
          - not_null

  - name: search_object_dim
    description: "Types of objects being searched for (e.g. drugs, weapons)."
    columns:
      - name: search_object
        tests:
          - unique
          - not_null
