WITH raw AS (
    SELECT 
    *
    FROM {{source('raw','IMD_2025_LSOA_STAGING')}}
)

SELECT 
CAST(LSOA_CODE_2021 AS STRING) AS lsoa21cd,
CAST(LSOA_NAME_2021 AS STRING) AS lsoa21nm,
CAST(INDEX_OF_MULTIPLE_DEPRIVATION_IMD_RANK_WHERE_1_IS_MOST_DEPRIVED AS NUMBER) AS imd_rank,
CAST(INDEX_OF_MULTIPLE_DEPRIVATION_IMD_DECILE_WHERE_1_IS_MOST_DEPRIVED_10PCT_OF_LSOA AS NUMBER) AS imd_decile
FROM RAW