with raw as (
    SELECT
    *
    FROM {{source('raw', 'STOP_SEARCH_STAGING')}}
)

SELECT 
CAST(AGE_RANGE AS STRING) AS age_range,
CAST(OUTCOME AS STRING) AS outcome, 
CAST(INVOLVED_PERSON AS BOOLEAN) AS involved_person,
CAST(SELF_DEFINED_ETHNICITY AS STRING) AS sde,
CAST(OFFICER_DEFINED_ETHNICITY AS STRING) AS ode,
CAST(GENDER AS STRING) AS gender,
CAST(LEGISLATION AS STRING) AS legislation, 
CAST(OUTCOME_LINKED_TO_OBJECT_OF_SEARCH AS BOOLEAN) AS outcome_linked_to_object,
CAST(REMOVAL_OF_MORE_THAN_OUTER_CLOTHING AS BOOLEAN) AS removal_clothing,
CAST(DATETIME AS DATETIME) AS search_date,
CAST(PARSE_JSON(LOCATION):latitude AS FLOAT) AS lat,
CAST(PARSE_JSON(LOCATION):longitude AS FLOAT) AS lon,
CAST(PARSE_JSON(LOCATION):street:id AS NUMBER) AS street_id,
CAST(PARSE_JSON(LOCATION):street:name AS STRING) AS street_name,
CAST(PARSE_JSON(OUTCOME_OBJECT):name AS STRING) AS search_outcome,
CAST(OPERATION AS STRING) AS operation,
CAST(TYPE AS STRING) AS search_type,
CAST(OPERATION_NAME AS STRING) AS operation_name,
CAST(OBJECT_OF_SEARCH AS STRING) AS search_object,
CAST(FORCE_NAME AS STRING) AS force_name
FROM raw