{{config(materialized='view')}}

WITH raw AS (
    SELECT 
    *
    FROM {{source('raw','IMD_2025_LSOA_STAGING')}}
)

SELECT 
LSOA_CODE_2021 AS LSOA21CD,
LSOA_NAME_2021 AS LSOA21NM,
INDEX_OF_MULTIPLE_DEPRIVATION_IMD_RANK_WHERE_1_IS_MOST_DEPRIVED AS imd_rank,
INDEX_OF_MULTIPLE_DEPRIVATION_IMD_DECILE_WHERE_1_IS_MOST_DEPRIVED_10PCT_OF_LSOA AS imd_decile
FROM RAW